import { AudienceClientContext } from "./audience.js";
import { TextPlanningPanel } from './text-planning.js';
import { useVisibleRefresh } from "./lifecycle.js";
import { useEffect, useRef, useState } from 'react';
import { MarketingRequestError, emptyBrief, STUDIO_STEPS, CAPABILITY_MATRIX, type BusinessBrief, type CampaignOption, type Commands, type MarketingClient, type StudioDraft, type StudioView, type StudioStep, type LibraryItem, type Workspace, type Material, type DraftMaterial, type StudioReport } from '../core/index.js';
import { GuidedFields, initialMaterial } from './guided.js';
const channelLabel = (provider:string) => ({meta:'Meta',linkedin:'LinkedIn',google:'Google Search'}[provider]??provider);
const humanize = (value:string) => value.toLowerCase().replaceAll('_',' ');
function FormatGuide({provider}:{provider:CampaignOption['provider']}) {
  const matrix=CAPABILITY_MATRIX[provider];
  return <div><p>{channelLabel(provider)} · API {matrix.apiVersion}. {provider==='google'?'Text-only Search ads. Artwork is not used.':'One image in the supported Feed placements.'}</p>{'combinations' in matrix&&<ul>{matrix.combinations.map((row,n)=><li key={n}>{row.map(humanize).join(' · ')}</li>)}</ul>}<p>Account eligibility, purpose restrictions and exact launch checks still apply.</p></div>;
}
const uuid=()=>crypto.randomUUID();
const option=():CampaignOption=>({title:'New approach',audienceHypothesis:'',offer:'',rationale:'',unknowns:[],provider:'meta',format:'single_image',destination:null,variants:[{headline:'',body:'',cta:''}]});
type Pending = { [K in 'saveBrief'|'saveCampaignOption'|'selectCampaignOption'|'saveStudioMaterial'|'selectStudioMedia'|'copyToDraft'|'setCampaignLifecycle'|'requestPlan'|'applyPlanningOption'|'promoteStudio'|'generateDraftMedia'|'reviewTextPlan'|'approveTextPlan']: {command:K;input:Commands[K]['input']} }['saveBrief'|'saveCampaignOption'|'selectCampaignOption'|'saveStudioMaterial'|'selectStudioMedia'|'copyToDraft'|'setCampaignLifecycle'|'requestPlan'|'applyPlanningOption'|'promoteStudio'|'generateDraftMedia'|'reviewTextPlan'|'approveTextPlan'];
interface LocalState { id:string; brief:BusinessBrief; option:CampaignOption; optionId?:string; material:DraftMaterial; step:StudioStep; revision:number; dirty:boolean; dirtyParts?:('brief'|'option'|'material')[]; pending:Pending|null; pendingImport?:{draftId:string;expectedRevision:number;requestKey:string;rights:string}; grantId:string }
const fresh=():LocalState=>({id:'',brief:emptyBrief(),option:option(),material:{name:'Untitled campaign'},step:'brief',revision:0,dirty:false,pending:null,grantId:'',pendingImport:undefined});
/** The same SDK-owned library/editor can be mounted independently of Workspace.
 * Storage is scoped to the authenticated workspace identity; no secrets are saved. */
export function CampaignStudio({client,workspace,onChanged,onConnections,onLaunch,onTracking,openDraftId,visible=true}: {client:MarketingClient;workspace:Workspace;onChanged?:(draft?:StudioDraft)=>Promise<void>;onConnections?:()=>void;onLaunch?:(id:string)=>void;onTracking?:(id:string)=>void;openDraftId?:string;visible?:boolean}) {
  const storage=`marketing:studio:v1:${workspace.project.id}:${workspace.planningScope??'unavailable'}`;
  return <AudienceClientContext.Provider value={client}><StudioContent key={storage} {...{client,workspace,onChanged,onConnections,onLaunch,onTracking,openDraftId,visible,storage}} /></AudienceClientContext.Provider>;
}
function StudioContent({client,workspace,onChanged,onConnections,onLaunch,onTracking,openDraftId,visible,storage}: {client:MarketingClient;workspace:Workspace;onChanged?:(draft?:StudioDraft)=>Promise<void>;onConnections?:()=>void;onLaunch?:(id:string)=>void;onTracking?:(id:string)=>void;openDraftId?:string;visible:boolean;storage:string}) {
  const [local,setLocal]=useState<LocalState>(()=>{try{const saved=sessionStorage.getItem(storage);if(saved){const v=JSON.parse(saved);if(v&&typeof v.id==='string'&&STUDIO_STEPS.includes(v.step))return v;}}catch{/* blocked storage remains manual */}return fresh();});
  const [view,setView]=useState<StudioView|null>(null),[items,setItems]=useState<LibraryItem[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState<'active'|'archived'|'trash'>('active'),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rights,setRights]=useState(''),[authority,setAuthority]=useState(''),[generationGrant,setGenerationGrant]=useState(''),[prompt,setPrompt]=useState(''),[report,setReport]=useState<StudioReport|null>(null),[conflict,setConflict]=useState<StudioDraft|null>(null),[deletion,setDeletion]=useState<Commands['reviewStudioDeletion']['output']|null>(null),[libraryLoading,setLibraryLoading]=useState(true);
  const [materialEpoch,setMaterialEpoch]=useState(0);
  const libraryReads=useRef(0),libraryScope=useRef({query,filter});libraryScope.current={query,filter};
  const readable=useRef(visible);readable.current=visible;
  const active=useRef(true),lock=useRef(false),heading=useRef<HTMLHeadingElement>(null),current=useRef(local);current.current=local;
  const canEdit=['admin','editor'].includes(workspace.role);
  function update(patch:Partial<LocalState>){if(patch.dirty||patch.grantId!==undefined)setReport(null);const touched=(['brief','option','material'] as const).filter(k=>patch[k]!==undefined);const dirtyParts=patch.dirty===false?[]:patch.dirty?[...new Set([...(current.current.dirtyParts??[]),...touched])]:current.current.dirtyParts;const next={...current.current,...patch,dirtyParts:patch.dirtyParts??dirtyParts};current.current=next;setLocal(next);try{sessionStorage.setItem(storage,JSON.stringify(next));}catch{setError('Browser recovery storage unavailable. Save before leaving this page.');}}
  useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
  async function library(next?:string){const request=++libraryReads.current,scope=libraryScope.current;const r=await client.call('listCampaigns',{query:scope.query,lifecycle:scope.filter,...(next?{cursor:next}:{})});if(active.current&&request===libraryReads.current&&scope.filter===libraryScope.current.filter&&scope.query===libraryScope.current.query){setItems(prev=>next?[...prev,...r.items]:r.items);setCursor(r.nextCursor);setLibraryLoading(false);}}
  useEffect(()=>{if(!visible)return;setLibraryLoading(true);const request=++libraryReads.current,abort=new AbortController();client.call('listCampaigns',{query,lifecycle:filter},{signal:abort.signal}).then(r=>{if(!abort.signal.aborted&&request===libraryReads.current){setItems(r.items);setCursor(r.nextCursor);setLibraryLoading(false);}}).catch(e=>{if(!abort.signal.aborted){setError(e.message);setLibraryLoading(false);}});return()=>abort.abort();},[client,filter,visible]);
  const pendingWork=visible?[...(view?.plans??[]).filter(r=>['queued','running'].includes(r.state)).map(r=>r.id),...(view?.jobs??[]).filter(j=>['queued','running','processing'].includes(j.state)).map(j=>j.id)].sort().join(':'):'';
  const refreshStudio=useVisibleRefresh(async signal=>{const draftId=current.current.id;if(!readable.current||!draftId)return;try{const v=await client.call('studio',{draftId},{signal});if(!signal.aborted&&active.current&&readable.current&&current.current.id===draftId){setView(v);if(!current.current.dirty&&!current.current.pending){const step=current.current.step;adopt(v.draft);update({step});}else if(v.draft.revision!==current.current.revision)setConflict(v.draft);}}catch(e){if(!signal.aborted&&active.current){setError((e as Error).message);if(/authentication_required|session_authority|forbidden/.test((e as Error).message)){setView(null);setItems([]);update(fresh());}}}},pendingWork);
  const wasVisible=useRef(false);
  useEffect(()=>{const returning=visible&&!wasVisible.current;wasVisible.current=visible;if(visible&&!lock.current&&(returning||view?.draft.id!==local.id))void refreshStudio();},[client,local.id,visible]);
  useEffect(()=>{if(visible)heading.current?.focus();},[local.step,visible]);
  useEffect(()=>{if(view&&!current.current.dirty)setReport(view.reports.filter(r=>r.draftId===view.draft.id&&r.revision===view.draft.revision).at(-1)??null);},[view]);
  function adopt(d:StudioDraft){const changedDraft=current.current.id!==d.id;if(changedDraft){setReport(null);setDeletion(null);setRights('');setPrompt('');setAuthority('');setGenerationGrant('');}update({...(changedDraft?{grantId:''}:{}),option:option(),optionId:undefined,id:d.id,brief:d.studio.brief,material:d.material,revision:d.revision,step:d.studio.step,dirty:false,pending:null});setConflict(null);}
  async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){if(active.current){const message=(e as Error).message;setError(message.replaceAll('_',' '));if(/authentication_required|session_authority|forbidden/.test(message)){setView(null);setItems([]);update(fresh());}}}finally{lock.current=false;if(active.current)setBusy(false);}}
  async function submit(intent:Pending){
    if(intent.command==='saveBrief'&&!intent.input.brief.name.trim()){heading.current?.parentElement?.querySelector<HTMLTextAreaElement>('textarea[aria-label="Campaign name"]')?.focus();throw new Error('Enter a campaign name before saving your brief.');}
    if(current.current.dirty&&!['saveBrief','saveCampaignOption','saveStudioMaterial'].includes(intent.command))throw new Error('Save or explicitly discard your edits before applying another selection or action.');
    if(current.current.pendingImport)throw new Error('Check the pending import before another change.');
    if(current.current.pending&&JSON.stringify(current.current.pending)!==JSON.stringify(intent))throw new Error('Resolve the pending save before a different change.');
    const before=current.current;const savedPart=({saveBrief:'brief',saveCampaignOption:'option',saveStudioMaterial:'material'} as Record<string,string>)[intent.command];const keep=(before.dirtyParts??[]).filter(k=>k!==savedPart);
    update({pending:intent});
    try{const result=await client.call(intent.command,intent.input as never);if(!active.current)return;const previousStep=current.current.step;
      if('studio'in result)adopt(result as StudioDraft);else {update({pending:null});}
      if(!readable.current)return;
      const returnedDraft='studio'in result?result as StudioDraft:undefined;
      if(returnedDraft&&view?.draft.id===returnedDraft.id){setView({...view,draft:returnedDraft});}
      else if(current.current.id&&intent.command!=='promoteStudio'){const v=await client.call('studio',{draftId:current.current.id});if(!active.current)return;setView(v);if(!current.current.dirty){adopt(v.draft);if(!returnedDraft)update({step:previousStep});}}
      if(keep.length)update({...Object.fromEntries(keep.map(k=>[k,before[k]])),...(keep.includes('option')?{optionId:before.optionId}:{}),dirty:true,dirtyParts:keep});
      if(returnedDraft&&view?.draft.id===returnedDraft.id&&items.some(item=>item.id===returnedDraft.id)&&!libraryScope.current.query&&libraryScope.current.filter===returnedDraft.studio.lifecycle){
        // The acknowledged draft contains every displayed row field. Preserve
        // pagination and ask the server again for searches or membership changes.
        setItems(rows=>rows.map(item=>item.id===returnedDraft.id?{...item,name:returnedDraft.material.name,revision:returnedDraft.revision,updatedAt:returnedDraft.studio.updatedAt,nextStep:returnedDraft.studio.step}:item).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.id.localeCompare(a.id)));
      }else if(returnedDraft||intent.command==='setCampaignLifecycle')await library();
      if(returnedDraft)await onChanged?.(returnedDraft);
      else if(intent.command==='promoteStudio'||intent.command==='setCampaignLifecycle')await onChanged?.();
      if(intent.command==='promoteStudio'&&'id'in result&&active.current&&readable.current)onLaunch?.(result.id);
    }catch(e){if(e instanceof MarketingRequestError&&e.status>=400&&e.status<500&&![408,429].includes(e.status))update({pending:null});if(active.current&&current.current.id){try{const v=await client.call('studio',{draftId:current.current.id});if(active.current){setView(v);if(v.draft.revision!==current.current.revision)setConflict(v.draft);}}catch{/* preserve pending intent */}}throw e;}
  }
  const change=()=>({draftId:local.id,expectedRevision:local.revision,requestKey:uuid()});
  async function open(item:LibraryItem){if(local.dirty||local.pending||local.pendingImport){setError('Your current edits are retained. Save, copy or explicitly discard them before opening another record.');return;}if(item.kind==='campaign'){await onChanged?.();if(active.current)onLaunch?.(item.id);return;}const v=await client.call('studio',{draftId:item.id});if(active.current){setView(v);adopt(v.draft);setReport(null);}}
  useEffect(()=>{
    if(!visible||!openDraftId||current.current.id===openDraftId)return;
    void run(async()=>{
      if(current.current.dirty||current.current.pending||current.current.pendingImport)throw new Error('Your edits are retained. Save or resolve them before opening the source draft.');
      const v=await client.call('studio',{draftId:openDraftId});
      if(active.current&&readable.current){setView(v);adopt(v.draft);}
    });
  },[visible,openDraftId]);
  const grant=workspace.grants.find(g=>g.id===local.grantId);
  const selected=view?.draft.studio.selection;
  const materialView=grant?{...initialMaterial(grant),...local.material,audience:{...initialMaterial(grant).audience,...local.material.audience},budget:{...initialMaterial(grant).budget,...local.material.budget}} as Material:null;
  const saveMaterial=()=>submit({command:'saveStudioMaterial',input:{...change(),material:{...local.material,assetIds:view?.draft.studio.assetIds??[]},step:local.step}});
  const step=(s:StudioStep)=>{if(!lock.current)update({step:s});};
  const reportCurrent=(!grant||!grant.revokedAt&&Date.parse(grant.expiresAt)>Date.now())&&report&&report.draftId===local.id&&report.revision===local.revision&&!local.dirty&&JSON.stringify(report.inputs.account??null)===JSON.stringify(grant??null);
  if(!visible)return null;
  return <section className="studio" aria-label="Campaign Studio">
    <div className="studio-library card"><div className="eyebrow">Campaign library</div><h2>Ideas to accountable campaigns</h2>
      <p>Save a brief without an account or AI. Every draft keeps its revisions and retained artwork.</p>
      <div className="studio-actions"><button onClick={()=>{if(local.dirty||local.pending||local.pendingImport){setError('Save or discard the current edits first.');return;}setView(null);setReport(null);update(fresh());}}>Start a brief</button><button className="secondary" onClick={onConnections}>Connections</button></div>
      <form onSubmit={e=>{e.preventDefault();void run(()=>library());}} className="studio-actions"><label>Search campaigns<input value={query} onChange={e=>setQuery(e.target.value)} /></label><button>Search</button><label>Library view<select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="active">Active</option><option value="archived">Archived</option><option value="trash">Trash</option></select></label></form>
      {libraryLoading&&<p role="status">Loading campaign library…</p>}{!libraryLoading&&!items.length&&<p>No records in this view. Start a brief or change the filter.</p>}
      <div className="studio-records">{items.map(item=><article key={item.id}><h3>{item.name}</h3><p>Revision {item.revision} · {item.kind} · {item.updatedAt||'Legacy record'}{item.providerState&&` · provider state ${item.providerState}`}</p><p>Next: {item.nextStep}</p>
        <div className="studio-actions"><button disabled={busy} onClick={()=>void run(()=>open(item))}>Open {item.name}</button>
        <button disabled={busy||!canEdit||!!local.pending||local.dirty} onClick={()=>void run(()=>submit({command:'copyToDraft',input:{id:item.id,kind:item.kind,expectedRevision:item.revision,requestKey:uuid()}}))}>Copy</button>
        <button disabled={busy||!canEdit||!!local.pending||!!local.pendingImport||local.dirty} onClick={()=>void run(()=>submit({command:'setCampaignLifecycle',input:{id:item.id,kind:item.kind,expectedRevision:item.revision,requestKey:uuid(),lifecycle:item.lifecycle==='active'?'archived':'active'}}))}>{item.lifecycle==='active'?'Archive':item.lifecycle==='trash'?'Restore':'Recover'}</button>
        {item.kind==='draft'&&item.lifecycle==='trash'&&<button onClick={()=>void run(async()=>setDeletion(await client.call('reviewStudioDeletion',{draftId:item.id,expectedRevision:item.revision})))}>Review deletion policy</button>}
        {item.kind==='draft'&&item.lifecycle!=='trash'&&<button className="secondary" disabled={busy||!canEdit||!!local.pending||!!local.pendingImport||local.dirty} onClick={()=>void run(()=>submit({command:'setCampaignLifecycle',input:{id:item.id,kind:item.kind,expectedRevision:item.revision,requestKey:uuid(),lifecycle:'trash'}}))}>Move to trash</button>}</div></article>)}</div>
      {deletion&&<aside aria-label="Permanent deletion policy"><h3>Permanent deletion unavailable</h3><p>{deletion.reason}</p><p>Retained: {deletion.retained.assets} selected asset references, {deletion.retained.revisions} revisions, {deletion.retained.planningRequests} planning requests and {deletion.retained.mediaJobs} media jobs.</p><p>{deletion.confirmationPolicy}</p></aside>}
      {cursor&&<button onClick={()=>void run(()=>library(cursor))}>More records</button>}
      {filter!=='active'&&<p>Archive and trash only change local visibility. Provider delivery, unknown operations, reservations, assets and history remain retained. Permanent deletion is unavailable: no exact host retention, hold, backup and impact policy is configured. Restore to continue; there is no automatic purge schedule.</p>}
    </div>
    {error&&<div role="alert" className="error">{error} <button disabled={busy} onClick={()=>void run(async()=>{await refreshStudio();await library();})}>Reload saved Studio</button></div>}
    {local.pendingImport&&<section className="card" aria-label="Import recovery"><h3>Import outcome needs review</h3><p>The original request identity is retained. Check saved bytes before choosing the same file again.</p><button disabled={busy} onClick={()=>void run(async()=>{const r=await client.call('studioImportStatus',{requestKey:local.pendingImport!.requestKey});if(r.asset){update({pendingImport:undefined});setView(await client.call('studio',{draftId:local.id}));}else setError('No retained result observed yet. Check again or choose the same original file to resume with its original key.');})}>Check import outcome</button></section>}
    {local.pending&&<section className="card" aria-label="Pending Studio save"><h3>Save outcome needs review</h3><p>The exact request is retained. Retry reads the same durable result; it does not create a new attempt.</p><button disabled={busy} onClick={()=>void run(()=>submit(local.pending!))}>Check pending save</button><p>Original action: {humanize(local.pending.command)}. Its exact inputs and request identity remain saved.</p>
      {conflict&&<button onClick={()=>update({pending:null})}>Keep edits and resolve revision conflict</button>}</section>}
    {conflict&&<section className="card"><h3>Newer saved revision {conflict.revision}</h3><p>Your unsaved values are still in the editor. Compare before reapplying; earlier approvals cannot be reused.</p><details><summary>Compare saved brief and material</summary><dl>{Object.entries({...conflict.studio.brief,headline:conflict.material.headline,body:conflict.material.body,materialDestination:conflict.material.destination,approaches:conflict.studio.options.map(o=>o.value.title)}).map(([field,value])=><div key={field}><dt>{humanize(field)}</dt><dd>{Array.isArray(value)?value.join('; '):value||'Not supplied'}</dd></div>)}</dl></details><button onClick={()=>{update({revision:conflict.revision,pending:null,dirty:true});setConflict(null);}}>Reapply my edits to this revision</button><button onClick={()=>adopt(conflict)}>Use saved revision</button></section>}
    <section className="card studio-editor"><nav aria-label="Studio steps" className="studio-steps">{STUDIO_STEPS.map((s,n)=><button key={s} aria-current={local.step===s?'step':undefined} disabled={busy} onClick={()=>step(s)}>{n+1}. {s}</button>)}</nav>
      <h2 tabIndex={-1} ref={heading}>{({brief:'Business brief',options:'Campaign options and copy',media:'Copy and retained artwork',checks:'Provider-fit preview and checks',tracking:'Tracking and launch handoff'})[local.step]}</h2>
      <p role="status" aria-live="polite">{busy?'Working…':local.dirty?'Unsaved edits retained in this browser tab':local.revision?`Saved revision ${local.revision}`:'New unsaved brief'} · {view?.draft.studio.lifecycle??'active'}</p>
      {!canEdit&&<p>Your current role can inspect this record. An editor can save changes.</p>}
      <fieldset disabled={!canEdit||busy||!!local.pending||view?.draft.studio.lifecycle==='archived'||view?.draft.studio.lifecycle==='trash'}>
      {local.step==='brief'&&<><div className="studio-fields">{([['name','Campaign name',100],['offer','Offer or product',4000],['audience','Intended audience',4000],['constraints','Constraints',4000],['direction','Creative direction and tone',1000]] as const).map(([field,label,max])=><label key={field}>{label}<textarea aria-label={label} maxLength={max} value={local.brief[field]} onChange={e=>update({brief:{...local.brief,[field]:e.target.value},dirty:true})}/></label>)}
        <label>Desired outcome<select value={local.brief.outcome} onChange={e=>update({brief:{...local.brief,outcome:e.target.value as BusinessBrief['outcome']},dirty:true})}><option value="acquisition">Customer acquisition</option><option value="recruitment">Recruitment</option></select></label>
        <label>Destination (HTTPS)<input value={local.brief.destination??''} onChange={e=>update({brief:{...local.brief,destination:e.target.value||null},dirty:true})}/></label><label>Supported facts / claims (one per line, up to 10)<textarea aria-label="Supported facts / claims" value={local.brief.facts.join('\n')} onChange={e=>update({brief:{...local.brief,facts:e.target.value.split('\n')},dirty:true})}/></label></div>
        <button onClick={()=>void run(()=>submit({command:'saveBrief',input:{...(local.id?{id:local.id,expectedRevision:local.revision}:{}),requestKey:uuid(),brief:local.brief}}))}>Save brief</button></>}
      {local.step!=='brief'&&!local.id&&<p>Save your business brief first. <button onClick={()=>step('brief')}>Return to brief</button></p>}
      {local.step==='options'&&local.id&&<>
        <p>Options are editable suggestions, not facts, approvals, account access or spending authority.</p><TextPlanningPanel client={client} draftId={local.id} revision={local.revision} dirty={local.dirty} reviews={view?.textReviews??[]} plans={view?.plans??[]} busy={busy} run={run} submit={submit} onRefresh={refreshStudio} onConnections={onConnections}/><div className="studio-options">{view?.draft.studio.options.map(o=><article key={o.id} className="card"><h3>{o.value.title}</h3><p>{channelLabel(o.value.provider)} · {humanize(o.value.format)} · {o.provenance.kind}{o.provenance.kind==='planning'&&o.provenance.edited?' · manually edited':''} · revision {o.revision}</p><p>{o.value.rationale}</p><p>Audience hypothesis: {o.value.audienceHypothesis}</p><p>Unknowns: {o.value.unknowns.join('; ')||'None supplied; review still required'}</p>{o.value.variants.map((v,n)=><div key={n}><h4>{v.headline||'Empty headline'}</h4><p>{v.body}</p><p>{v.cta}</p><button onClick={()=>void run(()=>submit({command:'selectCampaignOption',input:{...change(),optionId:o.id,optionRevision:o.revision,variant:n}}))}>{selected?.optionId===o.id&&selected.variant===n?'Selected':'Select copy'} {n+1}</button></div>)}<button className="secondary" onClick={()=>update({option:o.value,optionId:o.id,dirty:true})}>Edit option</button></article>)}</div>
        <h3>{local.optionId?'Edit approach':'Create an approach manually'}</h3><label>Option title<input value={local.option.title} onChange={e=>update({option:{...local.option,title:e.target.value},dirty:true})}/></label>
        <label>Channel and format<select value={local.option.provider} onChange={e=>{const provider=e.target.value as CampaignOption['provider'];update({option:{...local.option,provider,format:provider==='google'?'search_text':'single_image'},dirty:true});}}><option value="meta">Meta · single image Feed</option><option value="linkedin">LinkedIn · single image</option><option value="google">Google · Search text</option></select></label>
        <details><summary>Supported objectives for this format</summary><FormatGuide provider={local.option.provider}/></details><p>Choose a supported format before making media. Meta daily execution remains gated. LinkedIn requires account/Page roles, UTC and daily budget approval. xAI video is creative media; X advertising, document ads and video ads are unavailable.</p>
        {(['audienceHypothesis','offer','rationale'] as const).map(f=><label key={f}>{{audienceHypothesis:'Audience hypothesis',offer:'Offer',rationale:'Why this approach'}[f]}<textarea aria-label={f} value={local.option[f]} onChange={e=>update({option:{...local.option,[f]:e.target.value},dirty:true})}/></label>)}
        {local.option.variants.map((v,n)=><fieldset key={n}><legend>Copy variant {n+1}</legend>{(['headline','body','cta'] as const).map(f=><label key={f}>{{headline:'Headline',body:'Body',cta:'Call to action'}[f]}<textarea aria-label={f} value={v[f]} onChange={e=>update({option:{...local.option,variants:local.option.variants.map((old,j)=>j===n?{...old,[f]:e.target.value}:old)},dirty:true})}/></label>)}</fieldset>)}
        {local.option.variants.length<3&&<button onClick={()=>update({option:{...local.option,variants:[...local.option.variants,{headline:'',body:'',cta:''}]},dirty:true})}>Add copy variant</button>}
        <label>Option destination (HTTPS)<input value={local.option.destination??''} onChange={e=>update({option:{...local.option,destination:e.target.value||null},dirty:true})}/></label><label>Unknowns to review (one per line)<textarea value={local.option.unknowns.join('\n')} onChange={e=>update({option:{...local.option,unknowns:e.target.value.split('\n')},dirty:true})}/></label>
        <button onClick={()=>void run(async()=>{await submit({command:'saveCampaignOption',input:{...change(),...(local.optionId?{optionId:local.optionId}:{}),value:{...local.option,destination:local.option.destination??local.brief.destination}}});})}>Save option</button>
        
        <details><summary>Optional structured planning</summary><p>{view?.planning.reason}</p>{view?.planning.state==='fixture'&&<><label>Exact synthetic planning authority reference<input value={authority} onChange={e=>setAuthority(e.target.value)}/></label><button disabled={view?.planning.state!=='fixture'||!authority||local.dirty} onClick={()=>void run(()=>submit({command:'requestPlan',input:{...change(),authorityId:authority}}))}>Suggest options · one authorized attempt</button></>}
        {view?.plans.filter(r=>!r.textReceipt).map(r=><article key={r.id}><h4>{r.state} · {r.provider} / {r.model}</h4><p>{r.reason} · {r.id}</p><p>Usage: {r.usage.inputTokens??'unknown'} input / {r.usage.outputTokens??'unknown'} output tokens. Cost: {r.usage.cost?`${r.usage.cost.value} ${r.usage.cost.unit}`:'unavailable'}</p><button onClick={()=>void run(async()=>{await client.call('reconcilePlanning',{requestId:r.id});setView(await client.call('studio',{draftId:local.id}));})}>Check outcome</button>{r.options.map((o,n)=><article key={n}><h4>{o.title}</h4><p>{o.variants.map(v=>v.headline).join(' / ')}</p><button onClick={()=>void run(()=>submit({command:'applyPlanningOption',input:{...change(),requestId:r.id,optionIndex:n}}))}>Retain suggestion {n+1} for editing</button></article>)}</article>)}</details>
      </>}
      {local.step==='media'&&local.id&&<><h3>Selected copy</h3><p>Review supported objective and audience constraints before generation. <button onClick={()=>step('checks')}>Review account and audience</button></p><label>Headline<input value={local.material.headline??''} onChange={e=>update({material:{...local.material,headline:e.target.value},dirty:true})}/></label><label>Body<textarea aria-label="Body" value={local.material.body??''} onChange={e=>update({material:{...local.material,body:e.target.value},dirty:true})}/></label><button onClick={()=>void run(saveMaterial)}>Save copy</button>
        <h3>Retained artwork</h3><p>Import a single-frame JPEG, PNG or WebP up to 10 MiB / 40 megapixels. Rights are your attestation, not independent verification. Upload does not select an image.</p><label>Rights declaration<textarea aria-label="Rights declaration" value={rights} onChange={e=>setRights(e.target.value)}/></label><label>Import raster<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!client.importStudioRaster||!rights||local.dirty} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{if(!client.importStudioRaster)throw new Error('Host binary route is missing');const intent=current.current.pendingImport??{...change(),rights};update({pendingImport:intent});try{await client.importStudioRaster(intent,file);update({pendingImport:undefined});}catch(e){if(e instanceof MarketingRequestError&&e.status>=400&&e.status<500&&![408,429].includes(e.status))update({pendingImport:undefined});throw e;}setView(await client.call('studio',{draftId:local.id}));});}}/></label>
        {!client.importStudioRaster&&<p>Missing host binary route. Existing retained media can still be selected.</p>}
        <div className="studio-options">{view?.assets.map(a=><article key={a.id} className="card">{client.studioAssetUrl&&(a.kind==='image'?<img src={client.studioAssetUrl(a.id)} alt={`Retained ${a.source} artwork`}/>:<video src={client.studioAssetUrl(a.id)} controls preload="metadata"/>)}<p>{a.source} · {a.width}×{a.height} · {a.mime}</p><p>Rights: {a.rights.declaration}</p><details><summary>Artwork provenance</summary><p>Original owner: {a.owner.kind}. Rights attested {new Date(a.rights.at).toLocaleString()}.</p><code>{a.digest}</code></details><button disabled={local.dirty} onClick={()=>void run(()=>submit({command:'selectStudioMedia',input:{...change(),assetIds:[a.id]}}))}>{view.draft.studio.assetIds.includes(a.id)?'Selected artwork':'Select artwork'}</button></article>)}</div><button disabled={local.dirty} onClick={()=>void run(()=>submit({command:'selectStudioMedia',input:{...change(),assetIds:[]}}))}>Use text only / clear selection</button>
        <details><summary>Generate new artwork with separate authority</summary><label>Creative model<select value={generationGrant} onChange={e=>setGenerationGrant(e.target.value)}><option value="">Choose current generation authority</option>{view?.generationQuotes.map(g=><option key={g.grantId} value={g.grantId}>{g.kind} · {g.model} · {g.quote?`${g.quote.currency} ${g.quote.maxUnitMinor} minor units maximum`:'quote unavailable'}</option>)}</select></label><label>Artwork prompt<textarea aria-label="Artwork prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><p>One explicit attempt. Import rights declaration above also records generation rights. Unknown outcomes retain reservations; checking never regenerates.</p><button disabled={!view?.generationAvailable||!prompt||!rights||local.dirty||!view.generationQuotes.find(g=>g.grantId===generationGrant)?.quote} onClick={()=>void run(()=>submit({command:'generateDraftMedia',input:{...change(),grantId:generationGrant,prompt,rightsReceipt:rights,quoteReceipt:view!.generationQuotes.find(g=>g.grantId===generationGrant)!.quote!.receipt}}))}>Generate once</button></details>
        {view?.jobs.map(j=><article key={j.id}><h4>{j.kind} · {j.state}</h4><p>{j.reason} · retained request {j.providerRequestId??'not yet available'} · reservation {j.quote.currency} {j.quote.maxUnitMinor} minor units</p><button onClick={()=>void run(async()=>{await client.call('reconcileDraftMedia',{jobId:j.id});setView(await client.call('studio',{draftId:local.id}));})}>Check media outcome</button></article>)}
        <p>Image/video generation needs separate current model, session, custody and cost authority. Persistent generation is blocked; no automatic repair or regeneration. Retained video cannot launch through current adapters.</p>
      </>}
      {local.step==='checks'&&local.id&&<><p>Provider approximation · this is not provider approval or a delivery preview.</p><div className="creative-preview">{view?.assets.filter(a=>view.draft.studio.assetIds.includes(a.id)).map(a=>client.studioAssetUrl&&(a.kind==='video'?<video key={a.id} src={client.studioAssetUrl(a.id)} controls preload="metadata"/>:<img key={a.id} src={client.studioAssetUrl(a.id)} alt="Selected retained artwork"/>))}</div><h3>{local.material.headline}</h3><p>{local.material.body}</p><p>{local.material.destination}</p>
        <label>Account for provider fit<select value={local.grantId} onChange={e=>{const g=workspace.grants.find(g=>g.id===e.target.value);update({grantId:e.target.value,...(g?{material:{...initialMaterial(g),...local.material,audience:{...initialMaterial(g).audience,...local.material.audience,provider:g.provider},settings:local.material.settings?.accountId===g.accountId?local.material.settings:initialMaterial(g).settings},dirty:true}:{})});}}><option value="">Missing connection</option>{workspace.grants.map(g=><option key={g.id} value={g.id}>{g.label} · {channelLabel(g.provider)}</option>)}</select></label>
        {grant&&materialView?<details><summary>Account, identity, audience, budget and schedule</summary><GuidedFields key={materialEpoch} value={materialView} grant={grant} onChange={material=>update({material,dirty:true})}/></details>:<p>Save your idea now. Connect an account to complete provider-specific fields. <button onClick={onConnections}>Connect an advertising account</button></p>}
        <button onClick={()=>void run(saveMaterial)}>Save exact material</button><button disabled={!local.material.destination} onClick={()=>void run(async()=>{const captured=await client.call('captureDestination',{url:local.material.destination!});update({material:{...local.material,destinationDigest:captured.digest},dirty:true});})}>Capture destination evidence</button><button disabled={local.dirty} onClick={()=>void run(async()=>{const r=await client.call('checkStudio',{draftId:local.id,expectedRevision:local.revision,...(grant?{grantId:grant.id}:{})});setReport(r);})}>Run local checks</button>
        <p>Checks do not fetch destinations, generate media, send test events or write to an ad provider.</p>
        {report&&<div aria-label="Studio check report"><p>Checks for saved revision {report.revision}{!reportCurrent?' · Outdated: run checks for the current draft and account.':''}</p>{report.checks.map((c,n)=><p key={n}><strong>{{pass:'Complete',blocked:'Action needed',unknown:'Not verified'}[c.state]}</strong> · {c.message} <button onClick={()=>step(c.step)}>Review {c.step}</button></p>)}</div>}
        <details><summary>Shared supported capabilities</summary>{(['meta','linkedin','google'] as const).map(provider=><FormatGuide key={provider} provider={provider}/>)}</details>
      </>}
      {local.step==='tracking'&&local.id&&<><h3>Tracking: {reportCurrent&&report?.tracking.status==='passed'?'Test evidence saved — check current diagnostics':'Review source and test status'}</h3><button disabled={local.dirty} onClick={()=>onTracking?.(local.id!)}>Open Tracking setup and diagnostics</button><p>Desired outcome: {local.brief.outcome}. Material revision: {local.revision}. Destination: {local.material.destination||'Missing'}.</p><p>A configured pixel or conversion ID is not a successful test event. Website observation, collection, provider acceptance, matching and attribution need separate evidence.</p><button disabled={local.dirty} onClick={()=>void run(async()=>{setReport(await client.call('checkStudio',{draftId:local.id,expectedRevision:local.revision,...(grant?{grantId:grant.id}:{})}));})}>Save review handoff</button>{report&&<section aria-label="Saved handoff"><h3>Saved draft handoff</h3><p>{reportCurrent?'Saved and reviewable':'Outdated — prepare a new handoff for the current draft and account'} · revision {report.revision}</p><dl><dt>Campaign</dt><dd>{report.inputs.material.name}</dd><dt>Outcome</dt><dd>{report.tracking.outcome==='recruitment'?'Recruitment':'Customer acquisition'}</dd><dt>Destination</dt><dd>{report.tracking.destination||'Not supplied'}</dd><dt>Selected copy</dt><dd>{report.inputs.material.headline||'Not selected'}</dd><dt>Artwork</dt><dd>{report.inputs.assets.length} retained asset(s)</dd><dt>Tracking at review time</dt><dd>{report.tracking.status.replaceAll('_',' ')}{report.tracking.testStatus&&` · ${report.tracking.testStatus.reason}`}</dd></dl><p>Next: the site administrator connects the existing collector and records an authenticated test event for this destination and outcome. Account, budget and exact launch approvals remain separate.</p><details><summary>Technical handoff reference</summary><code>{report.inputDigest}</code></details></section>}
        {!grant&&<p>Connect an advertising account before creating a local campaign for launch review. Your saved draft and handoff are retained.</p>}<button disabled={!grant||local.dirty} onClick={()=>void run(()=>submit({command:'promoteStudio',input:{...change(),grantId:grant!.id,expectedGrantRevision:grant!.revision}}))}>Create local campaign for launch review</button>
        <p>Launch uses the existing exact-material preparation and approval pipeline. No ad is created or activated here. Missing tracking is not ready.</p><button className="secondary" onClick={()=>step('checks')}>Review launch dependencies</button></>}
      </fieldset>
      <div className="studio-actions"><button className="secondary" onClick={()=>step(STUDIO_STEPS[Math.max(0,STUDIO_STEPS.indexOf(local.step)-1)]!)}>Back</button><button className="secondary" onClick={()=>step(STUDIO_STEPS[Math.min(STUDIO_STEPS.length-1,STUDIO_STEPS.indexOf(local.step)+1)]!)}>Next</button><button className="secondary" disabled={!!local.pending||!!local.pendingImport} onClick={()=>{setMaterialEpoch(epoch=>epoch+1);if(view)adopt(view.draft);else update(fresh());setError('');}}>Discard unsaved edits / Cancel</button></div>
    </section>
  </section>;
}
