import { useEffect, useRef, useState } from 'react';
import { MarketingRequestError, TRACKING_OUTCOMES, type MarketingClient, type Workspace, type TrackingOwner, type TrackingOutcome, type TrackingView } from '../core/index.js';
import { useVisibleRefresh } from './lifecycle.js';

const labels = { missing_integration:'Missing integration', not_tested:'Not tested', pending:'Waiting for completion', passed:'First-party test passed', stale:'Review changes', cancelled:'Cancelled', expired:'Timed out' };
export function TrackingReadiness({client,owner,onOpen}:{client:MarketingClient;owner:TrackingOwner;onOpen:()=>void}) {
  const [view,setView]=useState<TrackingView|null>(null),[error,setError]=useState('');
  const refresh=useVisibleRefresh(async signal=>{try{const result=await client.call('tracking',{owner},{signal});if(!signal.aborted){setView(result);setError('');}}catch(e){if(!signal.aborted){setView(null);setError((e as Error).message);}}});
  return <section className="card"><h2>Tracking readiness</h2><p>{view?labels[view.readiness]:error?'Status unavailable':'Checking exact campaign configuration…'}</p><p>{view?.reason??error.replaceAll('_',' ')}</p><p>First-party testing does not authorize launch or verify provider delivery. Required conversion delivery remains unavailable.</p><div className="actions"><button onClick={onOpen}>Review Tracking diagnostics</button>{error&&<button onClick={()=>void refresh()}>Retry tracking status</button>}</div></section>;
}
/** SDK owns setup and recovery. Host supplies factual ports, never a wizard. */
export function MarketingTracking({client,workspace,initialOwner,onBack,onResults}:{client:MarketingClient;workspace:Workspace;initialOwner?:TrackingOwner;onBack?:()=>void;onResults?:()=>void}) {
  const items=[...workspace.drafts.map(d=>({kind:'draft' as const,id:d.id,name:d.material.name})),...workspace.campaigns.map(c=>({kind:'campaign' as const,id:c.id,name:c.material.name}))];
  const [owner,setOwner]=useState<TrackingOwner|undefined>(initialOwner??items[0]);
  if(!owner)return <section className="card"><h2>Tracking</h2><p>Save a campaign brief with a destination and desired outcome to configure tracking.</p><button onClick={onBack}>Open Campaign Studio</button></section>;
  return <section className="tracking"><div className="actions"><button className="secondary" onClick={onBack}>Back to Campaign Studio</button><button className="secondary" onClick={onResults}>Open Results</button></div><h2>Tracking</h2><label>Campaign or draft<select value={`${owner.kind}:${owner.id}`} onChange={e=>{const item=items.find(x=>`${x.kind}:${x.id}`===e.target.value);if(item)setOwner(item);}}>{items.map(x=><option key={`${x.kind}:${x.id}`} value={`${x.kind}:${x.id}`}>{x.name} · {x.kind}</option>)}</select></label><TrackingSetup key={`${workspace.planningScope}:${owner.kind}:${owner.id}`} client={client} owner={{kind:owner.kind,id:owner.id}} scope={workspace.planningScope??''}/></section>;
}
function TrackingSetup({client,owner,scope}:{client:MarketingClient;owner:TrackingOwner;scope:string}) {
  const key=`marketing-tracking:${scope}:${owner.kind}:${owner.id}`;
  const [saved] = useState(()=>{try{return JSON.parse(sessionStorage.getItem(key+':edits')??'null') as {sourceId:string;destinationId:string;outcome:TrackingOutcome;refund:boolean}|null;}catch{return null;}});
  const [view,setView]=useState<TrackingView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [sourceId,setSource]=useState(saved?.sourceId??''),[destinationId,setDestination]=useState(saved?.destinationId??''),[outcome,setOutcome]=useState<TrackingOutcome>(saved?.outcome??'inquiry');
  const [dirty,updateDirty]=useState(!!saved),[refund,setRefund]=useState(saved?.refund??false);
  const dirtyRef=useRef(dirty);
  const setDirty=(value:boolean)=>{dirtyRef.current=value;updateDirty(value);};
  useEffect(()=>{try{if(dirty)sessionStorage.setItem(key+':edits',JSON.stringify({sourceId,destinationId,outcome,refund}));else sessionStorage.removeItem(key+':edits');}catch{/* in-memory edits remain */}},[key,dirty,sourceId,destinationId,outcome,refund]);
  const life=useRef({active:true,serial:0});const heading=useRef<HTMLHeadingElement>(null);
  const pending=useRef<{command:'bindTracking'|'startTrackingTest';input:unknown}|null>(null);
  useEffect(()=>{life.current.active=true;try{pending.current=JSON.parse(sessionStorage.getItem(key)??'null');}catch{/* unavailable storage */}return()=>{life.current.active=false;life.current.serial++;};},[key]);
  const adopt=(next:TrackingView)=>{setView(next);if(!dirtyRef.current){setSource(next.binding?.source.id??next.sources[0]?.id??'');setDestination(next.binding?.destinationId??next.sources[0]?.destinations.find(d=>d.url===next.destination)?.id??'');setOutcome(next.binding?.outcome??(next.purpose==='recruitment'?'mou':'inquiry'));setRefund(next.binding?.refundTreatment==='gross_before_refunds');}};
  async function read(signal?:AbortSignal) {const serial=++life.current.serial;try{const next=await client.call('tracking',{owner},{signal});if(life.current.active&&!signal?.aborted&&serial===life.current.serial){adopt(next);setError('');}}catch(e){if(life.current.active&&!signal?.aborted&&serial===life.current.serial){setError((e as Error).message);setView(null);}}}
  const test=view?.tests.filter(t=>t.bindingRevision===view.binding?.revision).at(-1);
  const refresh=useVisibleRefresh(read,view?.readiness==='pending'?test?.id??'':'');
  useEffect(()=>{if(!test||!view||!['pending','passed'].includes(view.readiness))return;const timer=setTimeout(()=>setView(current=>current?{...current,readiness:'expired',reason:'Test evidence expired. Start a new no-send test with current authority.'}:current),Math.max(0,Date.parse(test.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[test?.id,test?.expiresAt,view?.readiness]);
  async function act(action:()=>Promise<unknown>) {setBusy(true);setError('');life.current.serial++;try{await action();if(life.current.active)await read();}catch(e){if(life.current.active)setError((e as Error).message);}finally{if(life.current.active)setBusy(false);}}
  async function durable(command:'bindTracking'|'startTrackingTest',input:unknown) {
    pending.current??={command,input};sessionStorage.setItem(key,JSON.stringify(pending.current));
    const operation=pending.current;
    try { await client.call(operation.command,operation.input as never); } catch(e) { if(e instanceof MarketingRequestError && e.status < 500 && ![408,429].includes(e.status)) { pending.current=null;sessionStorage.removeItem(key); } throw e; }
    pending.current=null;sessionStorage.removeItem(key);setDirty(false);
  }
  const source=view?.sources.find(s=>s.id===sourceId),destination=source?.destinations.find(d=>d.id===destinationId);
  const diagnostics=view?.diagnostics??[],latest=diagnostics.filter(d=>d.testId===test?.id).at(-1);
  return <><h3 ref={heading} tabIndex={-1}>Choose the outcome and source</h3><p>An inquiry is a completed submission. Qualification is a separate outcome. A page load or pixel request is not a completed submission.</p>
    {dirty&&<p role="status">Unsaved configuration changes are retained for this draft when you navigate or reload. Save them or cancel configuration changes before testing.</p>}
    {error&&<div role="alert" className="error">{error.replaceAll('_',' ')} <button disabled={busy} onClick={()=>void refresh()}>Retry status</button></div>}
    {!view&&!error&&<p role="status">Loading authorized tracking sources…</p>}
    {pending.current&&<section className="card"><h3>Save outcome needs review</h3><p>The request identity is retained. Check the same request before starting another.</p><button disabled={busy} onClick={()=>void act(()=>durable(pending.current!.command,pending.current!.input))}>Recover tracking request</button></section>}
    {view&&<><p>Purpose: {view.purpose==='recruitment'?'Recruitment':'Customer acquisition'} · Destination: {view.destination||'Missing from brief'}</p>
      {!view.sources.length&&<section className="card"><h3>Connect the existing site collector</h3><p>{view.reason}</p><p>The host needs an authorized site catalogue, destination ownership, authenticated completion/consent verification and no-send test destination. Saving a pixel ID cannot supply these capabilities.</p></section>}
      {!!view.sources.length&&<fieldset disabled={busy||!view.canEdit||!!pending.current}><legend>Authorized source configuration</legend>
        <label>Site or source<select value={sourceId} onChange={e=>{setSource(e.target.value);setDestination('');setDirty(true);}}>{view.sources.map(s=><option key={s.id} value={s.id}>{s.label} · {s.environment}</option>)}</select></label>
        <label>Owned destination<select value={destinationId} onChange={e=>{setDestination(e.target.value);setDirty(true);}}><option value="">Choose the exact campaign destination</option>{source?.destinations.map(d=><option key={d.id} value={d.id}>{d.label}{d.url!==view.destination?' · update brief to use this destination':''}</option>)}</select></label>
        <label>Completed outcome<select value={outcome} onChange={e=>{setOutcome(e.target.value as TrackingOutcome);setDirty(true);}}>{Object.entries(TRACKING_OUTCOMES).filter(([k,v])=>v.purpose===view.purpose&&source?.outcomes.includes(k as TrackingOutcome)).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
        {outcome==='purchase'&&<label className="check"><input type="checkbox" checked={refund} onChange={e=>{setRefund(e.target.checked);setDirty(true);}}/>Report completed paid receipts as gross revenue before refunds. Refund-adjusted revenue is unavailable.</label>}
        {source&&<><dl><dt>Domain / environment</dt><dd>{source.domain} · {source.environment}</dd><dt>Collector</dt><dd>{source.collector}{source.reason&&` · ${source.reason}`}</dd><dt>No-send test destination</dt><dd>{destination?.testUrl?'Available':'Ask the site administrator to expose a safe no-send interaction for this destination.'}</dd></dl><h4>Source installation and configuration</h4>{source.instructions.length?<ol>{source.instructions.map((line,n)=><li key={n}>{line}</li>)}</ol>:<p>No installation instructions supplied. Ask the site administrator to add source-specific collector instructions.</p>}</>}
        <button disabled={!source||!destination||destination.url!==view.destination||outcome==='purchase'&&!refund} onClick={()=>void act(()=>durable('bindTracking',{owner,expectedRevision:view.ownerRevision,expectedBindingRevision:view.binding?.revision??0,sourceId,sourceRevision:source!.revision,destinationId,outcome,refundTreatment:outcome==='purchase'?'gross_before_refunds':null,requestKey:crypto.randomUUID()}))}>Save tracking configuration</button>
        {dirty&&<button className="secondary" onClick={()=>{setDirty(false);setSource(view.binding?.source.id??view.sources[0]?.id??'');setDestination(view.binding?.destinationId??'');setOutcome(view.binding?.outcome??(view.purpose==='recruitment'?'mou':'inquiry'));setRefund(view.binding?.refundTreatment==='gross_before_refunds');}}>Cancel configuration changes</button>}
      </fieldset>}
      {!view.canEdit&&<p>A current human project administrator or editor can configure and test tracking.</p>}
      {view.binding&&<section className="card"><h3>{labels[view.readiness]}</h3><p role="status">{view.reason}</p><p>{TRACKING_OUTCOMES[view.binding.outcome].label} · {view.binding.source.label} · {view.binding.source.environment}</p>
        <p>{view.binding.promotedFrom && `Configuration retained from draft revision ${view.binding.promotedFrom.ownerRevision}, Tracking revision ${view.binding.promotedFrom.bindingRevision}. Draft QA remains historical; test this exact campaign configuration before relying on campaign readiness.`}</p><p>{view.binding.providerMapping?`Configured provider event: ${view.binding.providerMapping.provider} ${view.binding.providerMapping.event}. Account selection is configured. Pixel/conversion ownership and delivery are not verified here.`:'No provider pixel or conversion mapping is selected. First-party testing does not require a provider grant.'}</p>
        <div className="actions"><button disabled={busy||dirty||!view.canEdit||!!pending.current||view.readiness==='stale'||view.readiness==='pending'||view.readiness==='passed'} onClick={()=>void act(()=>durable('startTrackingTest',{owner,expectedBindingRevision:view.binding!.revision,requestKey:crypto.randomUUID()}))}>Start no-send test</button>
          <button className="secondary" disabled={busy} onClick={()=>void refresh()}>Refresh diagnostics</button>
          {test&&['pending','passed'].includes(view.readiness)&&<button className="secondary" disabled={busy} onClick={()=>void act(()=>client.call('cancelTrackingTest',{owner,testId:test.id}))}>Cancel test</button>}
        </div>
        {test&&view.readiness==='pending'&&<><p>Open the allowed destination and complete its no-send interaction before {new Date(test.expiresAt).toLocaleTimeString()}. The site server must send the authenticated completion receipt. Reload returns to this same test. Automatic checks are bounded; use Refresh diagnostics for a later result, or Cancel test to restart.</p><a className="tracking-destination" href={test.destinationUrl} target="_blank" rel="noreferrer">Open no-send test destination</a></>}
        <h4>Evidence stages</h4><dl><dt>Browser / site observation</dt><dd>{test?.observedAt?'Reported by a setup user · unverified observation only':latest?'Completed interaction reported by authenticated site collector':'Not observed'}</dd><dt>Authenticated local receipt</dt><dd>{latest?'Accepted · QA excluded · '+new Date(latest.receivedAt).toLocaleString():'Not received'}</dd><dt>Provider delivery / pixel firing</dt><dd>Unavailable. Configure and separately qualify a provider-specific transport; no conversions are sent by this test.</dd><dt>Matching diagnostics</dt><dd>Unavailable from provider. No match quality inferred.</dd><dt>Attribution</dt><dd>{latest?.attribution.campaignId?'Retained first-party paid-click attribution':'No eligible campaign click observed'} · last paid click · seven days</dd><dt>Production completeness</dt><dd>Separate authenticated collector checkpoints required. A passing test never creates coverage.</dd></dl>
      </section>}
      <section className="card"><h3>Retained test evidence</h3>{!diagnostics.length?<p>No authenticated test receipts yet. Browser observation alone will time out.</p>:<ul>{diagnostics.map(d=><li key={d.id}>{new Date(d.receivedAt).toLocaleString()} · {d.eligibleAtReceipt?'Eligible for the local test when received':'Late or stale diagnostic only'} · permanently excluded from business totals. Consent basis: {d.consentBasis}.<details><summary>Technical receipt reference</summary><code>{d.eventRef}</code></details></li>)}</ul>}</section>
    </>}
  </>;
}
